spring:
  application:
    name: registry-subscriber
  cloud:
    services:
      registrationMethod: route

security:
  basic:
    enabled: false

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
